### ISSUE TITLE
Kombu using deprecated importlib-metadata shims

### ISSUE THREAD

**Issue by syaffers** [celery/kombu#1600]
Hi devs,

I'm facing the following issue when importing kombu in my code. I've narrowed it down to the library `importlib-metadata`'s most recent release. Here's how to reproduce it:

1. Create a new virtual environment

```bash
python -m venv .venv
```

2. Activate virtual environment

```bash
source .venv/bin/activate
```

3. Install kombu

```bash
pip install kombu
```

4. Confirm that `importlib-metadata` release 5.0.0 is installed

```bash
pip freeze | grep importlib-metadata
```

5. Run python and import kombu via `kombu.entity`

```
>>> from kombu.entity import Queue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/muhammad.azman/Projects/drilling-management-ds/.venv2/lib/python3.7/site-packages/kombu/entity.py", line 7, in <module>
    from .serialization import prepare_accept_content
  File "/Users/muhammad.azman/Projects/drilling-management-ds/.venv2/lib/python3.7/site-packages/kombu/serialization.py", line 440, in <module>
    for ep, args in entrypoints('kombu.serializers'):  # pragma: no cover
  File "/Users/muhammad.azman/Projects/drilling-management-ds/.venv2/lib/python3.7/site-packages/kombu/utils/compat.py", line 82, in entrypoints
    for ep in importlib_metadata.entry_points().get(namespace, [])
AttributeError: 'EntryPoints' object has no attribute 'get'
```

It is stated in the most recent release of the library (https://github.com/python/importlib_metadata/blob/v5.0.0/CHANGES.rst)
> #97, #284, #300: Removed compatibility shims for deprecated entry point interfaces.

I can confirm kombu still works with the most recent release in v4 (e.g. 4.13.0).

Since this `importlib-metadata` release 5.0.0 is installed alongside a fresh kombu installation, this could be problematic for new users down the line. I'm suggesting to limit the version to <5.0.0 to ensure usability.

**Comment by syaffers** [comment]
Ah I should've mentioned, this happened on my Python 3.7.13. Works with no issues on 3.8.13.

**Comment by Aegdesil** [comment]
I get a probably related problem on Python 3.7 with kombu 5.2.4 when importing directly from kombu:

```
>>> from kombu import Consumer
Traceback (most recent call last):
  File "[...]/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
ImportError: cannot import name 'Consumer' from 'kombu' ([...]/lib/python3.7/site-packages/kombu/__init__.py)
```

I can confirm that reverting to importlib-metadata<5.0.0 works.
