### ISSUE TITLE
Import error with amqp==5.0.4

### ISSUE THREAD

**Issue by quimey** [celery/kombu#1290]
Installing kombu on a fresh virtualenv uses amqp version `5.0.4` and fails with the following error:

```
$ python
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kombu import Connection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quimey/test/.venv/lib/python3.7/site-packages/kombu/__init__.py", line 80, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "/home/quimey/test/.venv/lib/python3.7/site-packages/kombu/connection.py", line 21, in <module>
    from kombu import exceptions
  File "/home/quimey/test/.venv/lib/python3.7/site-packages/kombu/exceptions.py", line 5, in <module>
    from amqp import ChannelError, ConnectionError, ResourceError
  File "/home/quimey/test/.venv/lib/python3.7/site-packages/amqp/__init__.py", line 42, in <module>
    from .types import ChannelT, ConnectionT, MessageT
  File "/home/quimey/test/.venv/lib/python3.7/site-packages/amqp/types.py", line 13, in <module>
    from .spec import method_sig_t
ImportError: cannot import name 'method_sig_t' from 'amqp.spec' (/home/quimey/test/.venv/lib/python3.7/site-packages/amqp/spec.py)
```

It works well with `amqp==5.0.3`.

**Comment by ahopkins** [comment]
https://github.com/celery/py-amqp/issues/351

**Comment by auvipy** [comment]
please try https://pypi.org/project/amqp/5.0.5/ I accidentally merged some work from other branch and did not notice as it was not showing. extreamly sorry for that

**Comment by quimey** [comment]
Yes, that solves it, thanks!
